### ISSUE TITLE
Track.Seek not worked as expected

### ISSUE THREAD

**Issue by stefc** [jimm98y/SharpJaad#4]
If I use the Track.Seek(0.0) method to jump for example to the first frame of the track I get the Frame #3 instead. Also I only can use the method "ReadNextFrame()" that behind the curtain move the currentFrame counter to the next position. If I have a look on the source code it seems to me that I++ twice times is incremented once in the for loop and once in the assignment. This in my opinion is wrong? Also can you check for .GetTime() <= timeStep so if I seek to the beginning of the track I not loosing the first frame. For later frames is not necessary but for the first it would better fit. 

<img width="912" alt="image" src="https://github.com/jimm98y/SharpJaad/assets/464696/64715366-ac09-4749-8759-22750f7a007f">

Or should I try to create a pull request for that on my own ?

**Comment by jimm98y** [comment]
The pull request looked good to me, so I've merged it. The same issue was in the original Java code. The reason why I did not use the new C# features was to keep the code similar to the Java original, so that eventually the changes from here could be easily backported. But I like the clarity of the new syntax and in this case the original repo is no longer maintained anyway. Thank you very much!

**Comment by stefc** [comment]
Very fast backmerge thx, would your pipeline automatic push the change to nuget.org ? The next thought I've for seek is to switch to binary search ínstead of brute force because all frames are sorted by time. So you can select divide and conquer algorithm here 😀

**Comment by jimm98y** [comment]
Right now I had to build it and push it manually, the DevOps part is still something TBD in most of my repos.
